import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LeftSidebar from '@/components/shared/LeftSidebar'
import BottomSidebar from '@/components/shared/BottomSidebar'
import TopSidebar from '@/components/shared/TopSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopSidebar />
        <main className='flex '>


        <LeftSidebar />
        {children}
        </main>
        <BottomSidebar/>
        </body>
    </html>
  )
}
